name: me_adota
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5
  provider: ^6.0.5
  permission_handler: ^10.2.0
  phosphor_flutter: ^2.0.0
  go_router: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/src/shared/assets/svgs/

  fonts:
    - family: Archivo
      fonts:
        - asset: lib/src/shared/assets/fonts/Archivo-Regular.ttf
          weight: 400
        - asset: lib/src/shared/assets/fonts/Archivo-Medium.ttf
          weight: 500
        - asset: lib/src/shared/assets/fonts/Archivo-Bold.ttf
          weight: 700
